### PR TITLE
Use pull request target in gha

### PR DESCRIPTION
**Pull request by alonre24**
**Describe the changes in the pull request**

Replace pull_request with pull_request_target to enable forked PRs to run our basic flow which includes creating EC2 instance for  coverage flow (forked PRs still required maintainer approval to run)
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

**Mark if applicable**

- [ ] This PR introduces API changes
- [ ] This PR introduces serialization changes

### CODE REVIEW

**Review by GuyAv46 — COMMENTED** [review]
Nice
Shouldn't we fix the benchmark flow as well?

**Comment by alonre24** [comment]
> Nice Shouldn't we fix the benchmark flow as well? Also, the CI doesn't seem to run. Can we verify that it's because the target branch doesn't have the `pull_request_target` yet?

Will update the benchmark 
I verified - this is the reason why CI didn't run

**Review by GuyAv46 — APPROVED** [review]
LGTM
Requires force push right?

**Comment by alonre24** [comment]
> LGTM Requires force push right?

yes...

**Pull request merged**
